[package]
name = "airborne-pr"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
airborne-buildkite = { path = "../airborne-buildkite" }
airborne-core = { path = "../airborne-core" }
airborne-github = { path = "../airborne-github" }
airborne-runtime = { path = "../airborne-runtime" }
async-trait = "0.1"
chrono = "0.4"
tokio = { version = "1", features = ["sync"] }
url = "2"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
