import { useState } from "react";
import { AlertList } from "../components/AlertList";
import { WatchRow } from "../components/WatchRow";
import type { DashboardData, PipelineMapping, Rule, RuleInput } from "../types";

export function Dashboard({ data, mappings, refreshing, onRefresh, onAddWatch, onCreateRule, onUpdateRule, onDeleteRule, onRead, onReadAll, onOpen }: { data: DashboardData; mappings: PipelineMapping[]; refreshing: boolean; onRefresh: () => void; onAddWatch: (url: string) => Promise<void>; onCreateRule: (watchId: string, input: RuleInput) => Promise<void>; onUpdateRule: (rule: Rule, input: Partial<RuleInput>) => Promise<void>; onDeleteRule: (ruleId: string) => Promise<void>; onRead: (id: string) => void; onReadAll: () => void; onOpen: (url: string) => void }) {
  const [showAdd, setShowAdd] = useState(false); const [url, setUrl] = useState(""); const [adding, setAdding] = useState(false); const unread = data.alerts.filter(a => a.status === "unread").length;
  async function add(e: React.FormEvent) { e.preventDefault(); setAdding(true); try { await onAddWatch(url); setUrl(""); setShowAdd(false); } finally { setAdding(false); } }
  return <main className="dashboard"><header className="topbar"><div><p className="eyebrow">PR WATCHER</p><h1>Keep an eye on the next thing.</h1></div><button onClick={onRefresh} disabled={refreshing}>{refreshing ? "Refreshing…" : "↻ Refresh now"}</button></header>
    {data.last_poll_error && <div className="poll-error"><strong>Last poll failed.</strong> {data.last_poll_error}</div>}
    <section className="overview"><div className="metric"><strong>{data.watches.length}</strong><span>watched PR{data.watches.length === 1 ? "" : "s"}</span></div><div className="metric attention"><strong>{unread}</strong><span>unread alert{unread === 1 ? "" : "s"}</span></div><div className="metric"><strong>{data.last_poll_at ? new Date(data.last_poll_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : "—"}</strong><span>last poll</span></div></section>
    <section className="panel watches-panel"><div className="section-title"><div><p className="eyebrow">WATCHES</p><h2>Pull requests</h2></div><button onClick={() => setShowAdd(!showAdd)}>+ Add PR</button></div>{showAdd && <form className="add-watch" onSubmit={add}><input autoFocus required type="url" value={url} onChange={e => setUrl(e.target.value)} placeholder="https://github.com/owner/repo/pull/123" /><button disabled={adding}>{adding ? "Adding…" : "Add watch"}</button></form>}{data.watches.length ? <div className="watch-list">{data.watches.map(watch => <WatchRow key={watch.id} watch={watch} mappings={mappings} onCreateRule={onCreateRule} onUpdateRule={onUpdateRule} onDeleteRule={onDeleteRule} onOpen={onOpen} />)}</div> : <div className="empty"><h3>Start with a pull request</h3><p>Add a GitHub PR and choose the checks you want to hear about. Tokens live in Settings and stay in your Mac’s Keychain.</p><button onClick={() => setShowAdd(true)}>Add a PR</button></div>}</section>
    <section className="panel alerts-panel"><div className="section-title"><div><p className="eyebrow">ALERTS</p><h2>Recent activity</h2></div>{unread > 0 && <button className="secondary" onClick={onReadAll}>Mark all read</button>}</div><AlertList alerts={data.alerts} onRead={onRead} onOpen={onOpen} /></section>
  </main>;
}
