import { useEffect, useState } from "react";
import type { PipelineMapping, Settings as SettingsType } from "../types";

const blankMapping = (): PipelineMapping => ({ github_status_context: "", organization: "", pipeline: "", available_job_names: [] });
export function Settings({ initial, onSave }: { initial: SettingsType | null; onSave: (settings: SettingsType) => Promise<void> }) {
  const [settings, setSettings] = useState<SettingsType | null>(initial); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => setSettings(initial), [initial]);
  if (!settings) return <main className="settings"><p className="muted">Loading settings…</p></main>;
  const loaded = settings;
  function patch(update: Partial<SettingsType>) { setSaved(false); setSettings({ ...loaded, ...update }); }
  function patchMapping(index: number, update: Partial<PipelineMapping>) { const maps = loaded.pipelineMappings.map((item, i) => i === index ? { ...item, ...update } : item); patch({ pipelineMappings: maps }); }
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { await onSave(loaded); setSaved(true); } finally { setBusy(false); } }
  return <main className="settings"><header><p className="eyebrow">SETTINGS</p><h1>Connections and polling</h1><p className="muted">Tokens are saved only to your macOS Keychain.</p></header><form className="settings-form" onSubmit={submit}><section className="panel"><h2>Access tokens</h2><label>GitHub personal access token<input type="password" autoComplete="off" placeholder={loaded.githubTokenConfigured ? "Saved — enter a new token to replace" : "github_pat_…"} value={loaded.githubToken || ""} onChange={e => patch({ githubToken: e.target.value })} /></label><label>Buildkite token<input type="password" autoComplete="off" placeholder={loaded.buildkiteTokenConfigured ? "Saved — enter a new token to replace" : "bkua_…"} value={loaded.buildkiteToken || ""} onChange={e => patch({ buildkiteToken: e.target.value })} /></label></section><section className="panel"><h2>Polling</h2><label>Check every <div className="input-suffix"><input type="number" min="30" max="300" value={loaded.pollIntervalSeconds} onChange={e => patch({ pollIntervalSeconds: Number(e.target.value) })} /><span>seconds</span></div></label><p className="hint">Choose between 30 seconds and 5 minutes.</p></section><section className="panel"><div className="section-title"><h2>Buildkite pipelines</h2><button type="button" className="secondary" onClick={() => patch({ pipelineMappings: [...loaded.pipelineMappings, blankMapping()] })}>+ Add pipeline</button></div>{loaded.pipelineMappings.map((mapping, i) => <div className="mapping" key={i}><label>GitHub status context<input required value={mapping.github_status_context} onChange={e => patchMapping(i, { github_status_context: e.target.value })} placeholder="buildkite/discord-web" /></label><label>Organization<input required value={mapping.organization} onChange={e => patchMapping(i, { organization: e.target.value })} /></label><label>Pipeline<input required value={mapping.pipeline} onChange={e => patchMapping(i, { pipeline: e.target.value })} /></label><label>Suggested job names<input value={mapping.available_job_names.join(", ")} onChange={e => patchMapping(i, { available_job_names: e.target.value.split(",").map(x => x.trim()).filter(Boolean) })} placeholder="Web lint, Upload build override" /></label><button type="button" className="danger" onClick={() => patch({ pipelineMappings: loaded.pipelineMappings.filter((_, index) => index !== i) })}>Remove</button></div>)}</section><footer className="save-bar">{saved && <span>Saved.</span>}<button disabled={busy}>{busy ? "Saving…" : "Save settings"}</button></footer></form></main>;
}
